version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
     jobs:
      post_checkout:
        - git fetch --unshallow || true
        - git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*' || true
        - git fetch --all --tags || true

python:
  install:
    - requirements: docs/requirements.txt
    # Install our python package before building the docs
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub
